branch-defaults:
  default:
    environment: flask-env
    group_suffix: null
  master:
    environment: flask-env2
global:
  application_name: flask-app-1
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.4
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
